dishes/urls.py
from django.urls import path
from dishes import views

app_name = 'dishes'

urlpatterns = [
    path('cart', views.CartListView.as_view(), name='cart'),
    path('get_cart_items', views.get_cart_items, name='get-cart-items'),
    path('remove_from_cart', views.remove_from_cart, name='remove-from-cart'),
    path('add_to_cart', views.add_dish_to_cart, name='add-dish-to-cart'),
    path('order/<int:pk>/recap', views.OrderRecapView.as_view(), name='order-recap'),
    path('order/<int:pk>/complete', views.OrderCompleteView.as_view(), name='order-complete'),
    path('order/<int:pk>/detail', views.OrderDetailView.as_view(), name='order-detail'),
    path('order/list', views.OrderListView.as_view(), name='order-list'),

    path('review/add/<int:pk>', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>/detail', views.ReviewDetailView.as_view(), name='review-detail'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),

    path('menu', views.MenuView.as_view(), name='menu'),
    path('dish/add', views.DishAddView.as_view(), name='add-dish'),
    path('dish/<int:pk>/detail', views.DishDetailView.as_view(), name='dish-detail'),
    path('dish/<int:pk>/update', views.DishUpdateView.as_view(), name='dish-update'),
    path('dish/<int:pk>/delete', views.DishDeleteView.as_view(), name='dish-delete'),
    path('dish/search', views.search_dishes, name='dish-search'),
    path('dish/search/view', views.DishSearchView.as_view(), name='dish-search-view'),
]

restaurant_project/urls.py
import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from restaurant_project import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('dishes/', include('dishes.urls')),
    path('user_management/', include('user_management.urls')),
    path('user_management/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/models.py
from statistics import mean

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from restaurant_project import settings


class Dish(models.Model):
    """
    Model that represent a dish, a dish is created by the manager account.
    """
    images_path = 'uploads/'
    MAIN = 'MD'
    BURGER = 'BU'
    SIDE = 'SI'
    DESSERT = 'DE'
    CATEGORY_CHOICES = [
        (MAIN, _('Piatto principale')),
        (BURGER, _('Burger')),
        (SIDE, _('Contorno')),
        (DESSERT, _('Dessert')),
    ]
    name = models.CharField(max_length=150, unique=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=MAIN)
    ingredients = models.TextField(max_length=255)
    cook_time = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.ImageField(upload_to=images_path,
                              default=images_path + 'bread.png')

    @classmethod
    def get_dish_categories(cls):
        """
        Returns a dictionary with all the possible categories of a dish as keys and
        empty arrays as values.
        :return: a dictionary with a set of empty arrays for each category.
        """
        return {category: [] for category, description in cls.CATEGORY_CHOICES}

    @property
    def get_reviews(self):
        """
        Returns all the reviews associated to the current dish.
        :return: The review queryset.
        """
        return Review.objects.filter(dish=self)

    @property
    def get_avg_revs(self):
        """
        Returns the average score of the reviews related to the dish.
        :return: The average value rounded to one decimal position.
        """
        revs_list = Review.objects.filter(dish=self).values_list('stars', flat=True)
        return round(mean(revs_list), 1) if len(revs_list) > 0 else 0

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['-pk']
        verbose_name_plural = _('Dishes')


class Review(models.Model):
    """
    Model that represent a Review for a Dish, a review is written by a registered user.
    """
    title = models.CharField(max_length=150)
    stars = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_reviews')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name='dish_reviews')
    comment = models.TextField(max_length=2000)
    date = models.DateTimeField(default=timezone.now)

    def __repr__(self):
        return f'[ {self.title} - {self.stars} ] di {self.user}'

    def __str__(self):
        return f'[ {self.title} - {self.stars} ] di {self.user}'

    class Meta:
        ordering = ['-date']


class OrderHeader(models.Model):
    """
    Model that represent an Order, every order is created as a CART when the
    user create his profile or when he complete an order from the "Cart" page.
    """
    CART = 'CA'
    ORDERED = 'OR'
    PROCESSED = 'PR'
    SHIPPED = 'SH'  # at home
    READY = 'RE'  # takeaway
    DONE = 'DO'
    ORDER_STATES = [
        (CART, _('Carrello')),
        (ORDERED, _('Ordinato')),
        (PROCESSED, _('In preparazione')),
        (READY, _('Pronto')),
        (SHIPPED, _('In consegna')),
        (DONE, _('Completato')),
    ]
    code = models.CharField(max_length=150, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_orders')
    amount = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    state = models.CharField(max_length=2, choices=ORDER_STATES, default=CART)
    delivery_type = models.BooleanField(default=False)  # False --> takeaway, True --> at home
    date = models.DateTimeField(default=timezone.now)
    date_change_state = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(max_length=255, null=True, blank=True)

    @property
    def get_items(self):
        """
        Gets all the items associated to the current order (self).
        :return: queryset of the items associated to the current order.
        """
        return OrderItem.objects.filter(order=self)

    @property
    def get_items_count(self):
        """
        Gets number of the pieces of the items associated to the current order.
        :return: number of the pieces (integer).
        """
        return sum(OrderItem.objects.filter(order=self).values_list('pieces', flat=True))

    @property
    def get_amount(self):
        """
        Gets the amount of the current order, based on the sum of the price of
        all the order items.
        :return: total amount (integer)
        """
        return sum(list(OrderItem.objects.filter(order=self).values_list('price', flat=True)))

    @property
    def get_lexical_state(self):
        """
        Retrieves the lexical version of the current order state.
        :return: The description of the order state.
        """
        return [description
                for state, description in OrderHeader.ORDER_STATES
                if state == self.state][0]

    def __str__(self):
        return f'Ordine in stato {self.state} di {self.user}'

    def __repr__(self):
        return f'Ordine in stato {self.state} di {self.user}'

    class Meta:
        ordering = ['-date_change_state']


class OrderItem(models.Model):
    """
    Model that represent an order item, an order item is created when a user
    add a new dish in the cart.
    """
    order = models.ForeignKey(OrderHeader, on_delete=models.CASCADE, related_name='order_items')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name='dish_orders')
    pieces = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    notes = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return f'Elemento {self.dish} dell\'ordine {self.order}'

    def __repr__(self):
        return f'Elemento {self.dish} dell\'ordine {self.order}'

dishes/forms.py
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Row, Column, Submit, Field
from django import forms
from django.utils.translation import gettext_lazy as _

from dishes.models import Dish, OrderHeader, Review


class DishForm(forms.ModelForm):
    """
    Form used to create or update a dish.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['name'].widget.attrs['placeholder'] = _('Nome piatto')
        self.fields['ingredients'].widget.attrs['placeholder'] = _('Lista degli ingredienti...')
        self.fields['cook_time'].widget.attrs['placeholder'] = _('Tempo di preparazione')
        self.fields['price'].widget.attrs['placeholder'] = _('Prezzo del piatto')
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'dish-add-crispy-form'
        self.helper.form_class = ''
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='col-md-6 mb-0'),
                Column(Field('category', css_class='custom-select'), css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(Column('image', css_class='mb-0'), css_class='grey-text'),
            Row(
                Column(AppendedText('cook_time', 'min', active=True), css_class='col-md-6 mb-0'),
                Column(AppendedText('price', '€', active=True), css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(Column(Field('ingredients', type='textarea'), css_class='mb-0'), css_class='grey-text'),
            Submit('submit', _('Salva'), css_class='btn btn-info'),
            Submit('cancel', _('Annulla'), css_class='btn btn-danger', formnovalidate='formnovalidate'),
        )

    class Meta:
        model = Dish
        fields = (
            'name',
            'category',
            'ingredients',
            'cook_time',
            'price',
            'image',
        )
        labels = {
            'name': 'Nome del piatto',
            'category': 'Categoria',
            'ingredients': 'Ingredienti',
            'cook_time': 'Tempo di preparazione (min)',
            'price': 'Prezzo',
            'image': 'Foto del piatto',
        }


class OrderHeaderForm(forms.ModelForm):
    """
    Form to update an order state (if the user is a manager).
    """
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('initial', None).pop('user', None)
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['code'].disabled = True
        self.fields['amount'].disabled = True
        if not user.is_manager:
            self.fields['state'].disabled = True
        self.fields['delivery_type'].disabled = True
        self.fields['date'].disabled = True
        self.fields['notes'].disabled = True
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'order-detail-crispy-form'
        self.helper.form_class = ''
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(
                Column('code', css_class='col-md-6 mb-0'),
                Column(AppendedText('amount', '€', active=True), css_class='col-md-3 mb-0'),
                Column('delivery_type', css_class='col-md-3 mb-0 pl-5 mt-4 custom-control custom-switch'),
                css_class='d-flex align-items-center grey-text'
            ),
            Row(
                Column(Field('state', css_class='custom-select'), css_class='col-md-6 mb-0'),
                Column('date', css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(
                Column(Field('notes', type='textarea', rows="3"), css_class='mb-0'), css_class='grey-text'
            )
        )
        if kwargs['instance'].delivery_type:
            self.helper.layout.append(
                HTML("""
                    <hr>
                    <h4 class="font-weight-light">
                        Tempo di consegna previsto: {{ orderheader|get_preparation_time:orderheader.user }} minuti 
                        <i class="far fa-clock"></i>
                    </h4>
                """)
            )
        else:
            self.helper.layout.append(
                HTML("""
                    <hr>
                    <h4 class="font-weight-light">
                        Tempo di preparazione previsto: {{ orderheader|get_preparation_time:orderheader.user }} minuti 
                        <i class="far fa-clock"></i>
                    </h4>
                """)
            )
        if user.is_manager:
            self.helper.add_input(Submit('submit', _('Aggiorna'), css_class='btn btn-info'))
            self.helper.add_input(Submit('cancel', _('Annulla'),
                                         css_class='btn btn-danger',
                                         formnovalidate='formnovalidate'))

    class Meta:
        model = OrderHeader
        fields = (
            'code',
            'amount',
            'state',
            'delivery_type',
            'date',
            'notes',
        )
        labels = {
            'code': 'Codice ordine',
            'amount': 'Totale',
            'state': 'Stato ordine',
            'delivery_type': 'Domicilio',
            'date': 'Data ordine',
            'notes': 'Note',
        }


class ReviewForm(forms.ModelForm):
    """
    Form used to create or update a review.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['title'].widget.attrs['placeholder'] = _('Titolo')
        self.fields['comment'].widget.attrs['placeholder'] = _('Scrivi la tua esperienza...')
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'review-add-crispy-form'
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(HTML(
                """
                    <label>Valutazione complessiva *</label>
                    <div class="form-group">
                        <fieldset class="rating">
                            <input type="radio" id="star5" name="stars" value="5" />
                            <label for="star5">5 stars</label>
                            <input type="radio" id="star4" name="stars" value="4" />
                            <label for="star4">4 stars</label>
                            <input type="radio" id="star3" name="stars" value="3" />
                            <label for="star3">3 stars</label>
                            <input type="radio" id="star2" name="stars" value="2" />
                            <label for="star2">2 stars</label>
                            <input type="radio" id="star1" name="stars" value="1" />
                            <label for="star1">1 star</label>
                        </fieldset>
                    </div>
                """
            ), css_class='d-flex flex-column grey-text'),
            Row(
                Column('title', css_class='col-md mb-0'), css_class='grey-text'
            ),
            Row(
                Column(Field('comment', type='textarea', rows="5"), css_class='mb-0 grey-text'),
            ),
            Submit('submit', _('Salva'), css_class='btn btn-info'),
            Submit('cancel', _('Annulla'), css_class='btn btn-danger', formnovalidate='formnovalidate'),
        )

    class Meta:
        model = Review
        fields = (
            'title',
            'stars',
            'comment'
        )
        labels = {
            'title': 'Titolo',
            'stars': 'Voto',
            'comment': 'Commento'
        }

dishes/templates/dishes/cart.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% comment %}
    Template to display the cart page.
{% endcomment %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.min.css">
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        /* Page specific */
        .jumbotron {
            background-image: url("{% static 'img/varun-tandon-NkkHNWKhDd4-unsplash.jpg' %}");
            background-size: cover;
        }
        .list-link {
            color: #777;
        }
    </style>
{% endblock %}

{% block title %}Carrello{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Carrello</h2>
            <p class="lead">Preparati ad assaporare i nostri piatti, manca poco!</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% include 'dishes/base/cart_modal.html' %}
    <div class="box-width-radius2 container-md shadow mb-3 pl-10 bg-white w-auto">
        <ul class="list-group list-group-flush dish-list">
            {% for item in orderitem_list %}
                {% include 'dishes/base/base_cart_item.html' with item=item dish=dishes|get_dish_from_list:forloop.counter0 %}
            {% empty %}
                <li class="dish-content list-group-item text-center">
                    <p class="lead">Nessun elemento nel carrello, visualizza il nostro menu!</p>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% if orderitem_list %}
        {% include 'dishes/base/base_order_confirmation.html' %}
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.min.js"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    {% include 'dishes/base/add_to_cart_ajax.html' %}
    {% include 'dishes/base/remove_from_cart_ajax.html' %}
    <script>
        $(function () {
            $('#deliveryType').on('change', function () {
                $('.tooltip-test').toggle()
                if ($(this).is(':checked')) {
                    $('label[for=' + $(this).attr('id') + ']').text('Consegna a domicilio');
                } else {
                    $('label[for=' + $(this).attr('id') + ']').text('Asporto');
                }
            });
        });
    </script>
{% endblock %}

dishes/templates/dishes/dish_add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Template to display the add dish page.
{% endcomment %}

{% block title %}Nuovo piatto{% endblock %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        /* Page specific */
        .jumbotron {
            background-image: url("{% static 'img/hermes-rivera-Ww8eQWjMJWk-unsplash.jpg' %}");
            background-size: cover;
        }
        #id_ingredients {
            height: 65px;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Aggiungi un nuovo piatto</h2>
            <p class="lead">Inserire tutte le informazioni richieste.</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 pl-10 bg-white w-auto">
        {% crispy form %}
    </div>
{% endblock %}

dishes/templates/dishes/dish_delete.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% comment %}
    Template to display the delete dish page.
{% endcomment %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        /* Page specific */
        .jumbotron {
            background-image: url("{% static 'img/hermes-rivera-Ww8eQWjMJWk-unsplash.jpg' %}");
            background-size: cover;
        }
    </style>
{% endblock %}

{% block title %}Eliminazione piatto{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Eliminazione piatto: {{ dish.name }}</h2>
            <p class="lead">Perderai tutte le informazioni e le recensioni ad esso collegate.</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 pl-10 bg-white w-auto">
        <h1 class="font-weight-light">Sicuro di eliminare questo piatto?</h1>
        <p>Questa azione non sarà reversibile. Oltre al piatto verranno cancellati tutti i dati ad esso collegati (recensioni, ordini, ecc.).</p>
        <form method="post">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Elimina">
            <a class="btn btn-success" href="{% url 'dishes:dish-detail' dish.pk %}">
                Annulla
            </a>
        </form>
    </div>
{% endblock %}

dishes/templates/dishes/dish_detail.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% comment %}
    Template to display the detail of a dish.
{% endcomment %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.min.css">
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        /* Page specific */
        .jumbotron {
            background-image: url("https://res.cloudinary.com/dag3t3qu8/image/upload/q_auto/v1645219450/spooncorner/hermes-rivera-Ww8eQWjMJWk-unsplash_eanzeb.jpg");
            background-size: cover;
        }
        .dish-img {
            background-image: url('{{ dish.image.url }}');
            background-size: cover;
            background-repeat: no-repeat;
            max-width: 225px;
            overflow: hidden;
            border-top-left-radius: 10px;
            border-bottom-left-radius: 10px;
        }
    </style>
{% endblock %}

{% block title %}Dettagli piatto{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Piatto: {{ dish.name }}</h2>
            <p class="lead">Visualizza i dettagli del piatto e le recensioni di altri clienti.</p>
            {% if user.is_authenticated and user.is_manager %}
                <div class="row">
                    <div class="col d-flex justify-content-end">
                        <a href="{% url 'dishes:dish-update' dish.pk %}" class="btn btn-lg btn-info"><i class="fas fa-pen"></i> Modifica piatto</a>
                    </div>
                    <div class="col d-flex justify-content-start">
                        <a href="{% url 'dishes:dish-delete' dish.pk %}" class="btn btn-lg btn-danger"><i class="fas fa-trash"></i> Elimina piatto</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block content %}
    {% include 'dishes/base/cart_modal.html' %}
    <div class="box-width-radius2 container-md shadow mb-3 pl-10 bg-white w-auto">
        <div class="row">
            <div class="col dish-img"></div>
            <div class="col p-4 dish-content">
                <h5 class="d-flex justify-content-between">
                    <span class="dish-title">{{ dish.name }}</span>
                    <span class="d-flex justify-content-start">{{ dish.get_avg_revs }} &nbsp;<i class="fas fa-star"></i></span>
                </h5>
                <p class="price">{{ dish.price }} €</p>
                <p><strong>Ingredienti:</strong> {{ dish.ingredients }}</p>
                <p>
                    <small class="text-muted">
                        Tempo di preparazione: {{ dish.cook_time }} min
                    </small>
                </p>
                {% if user.is_authenticated %}
                    <a href="#cart-modal" class="card-link cart-link" data-toggle="modal" data-target="#cart-modal">
                        <span>Aggiungi al carrello <i class="fas fa-shopping-cart"></i></span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="box-width-radius2 container-md shadow p-4 mb-3 pl-10 bg-white w-auto">
        <div class="row d-flex justify-content-between align-items-center">
            <div class="col">
                <h4 class="font-weight-light">Recensioni</h4>
            </div>
            {% if user.is_authenticated %}
                <div class="col d-flex justify-content-end">
                    <a href="{% url 'dishes:review-add' dish.pk %}" class="btn btn-outline-primary">Scrivi una recensione <i class="fas fa-pen"></i></a>
                </div>
            {% endif %}
        </div>
        <hr>
        <ul class="list-group list-group-flush">
            {% for review in reviews %}
                <li class="list-group-item break-word">
                    {#                    <a href="{% url 'dishes:review-detail' review.pk %}" class="d-flex justify-content-between align-items-center list-link review-link">#}
                    {#                        <div>#}
                    {#                            <div>#}
                    {#                                <span>{{ review.title }} - {{ review.stars }} <i class="fas fa-star"></i></span>#}
                    {#                                <span>[ {{ review.date|date:'d/m/Y' }} ]</span>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                        <div>#}
                    {#                            <span>Autore: {{ review.user }}</span>#}
                    {#                        </div>#}
                    {#                    </a>#}
                    <a href="{% url 'dishes:review-detail' review.pk %}" class="list-link review-link">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="col-lg-6 col-12">
                                <div class="row d-flex flex-column">
                                    <div class="col col-lg col-12">
                                        <span>{{ review.title }} - {{ review.stars }} <i class="fas fa-star"></i></span>
                                    </div>
                                    <div class="col col-lg col-12">
                                        <span>[ {{ review.date|date:'d/m/Y' }} ]</span>
                                    </div>
                                </div>
                            </div>
                            <!-- <div class="col-lg-4 col-12"></div> -->
                            <div class="col-lg-6 col-12 d-flex justify-content-end">
                                <div class="row d-flex flex-column">
                                    <div class="col col-lg col-12">
                                        <span><i class="fas fa-user"></i> {{ review.user.profile.first_name }} {{ review.user.profile.last_name }}</span>
                                    </div>
                                    <div class="col col-lg col-12">
                                        <span><i class="fas fa-envelope"></i> {{ review.user }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="break-word">

                        </div>
                    </a>
                </li>
            {% empty %}
                <p>Ancora nessuna recensione!</p>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.min.js"></script>
    <script src="{% static 'js/cart.js' %}"></script>
{% endblock %}

dishes/templates/dishes/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}
{% load crispy_forms_tags %}

{% comment %}
    Template to display the review detail page.
{% endcomment %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        /* Page specific */
        .jumbotron {
            background-image: url("https://res.cloudinary.com/dag3t3qu8/image/upload/q_auto/v1645219450/spooncorner/hope-house-press-leather-diary-studio-PJzc7LOt2Ig-unsplash_pfmoqi.jpg");
            background-size: cover;
        }
    </style>
{% endblock %}

{% block title %}Dettagli Recensione{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Recensione: {{ review.dish }}</h2>
            <p class="lead">Leggi l'esperienza degli altri utenti.</p>
            <p class="lead">
                <a href="{% url 'dishes:dish-detail' review.dish.pk %}" class="btn btn-lg btn-secondary"><i class="fas fa-arrow-left"></i> &nbsp; Indietro</a>
            </p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow mb-3 p-3 pl-10 bg-white w-auto">
        <div class="d-flex flex-column">
            <div class="row d-flex justify-content-between align-items-center">
                <div class="col">
                    <h4 class="font-weight-light">
                        {{ review.title }} - {{ review.stars }} <i class="fas fa-star"></i>
                    </h4>
                </div>
                <div class="col d-flex justify-content-end">
                    {% if review.user == user %}
                        <div>
                            <a href="{% url 'dishes:review-update' review.pk %}" class="btn btn-sm btn-info"><i class="fas fa-pen"></i></a>
                            <a href="{% url 'dishes:review-delete' review.pk %}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span class="font-weight-light grey-text"></span>
                    <span class="font-weight-light grey-text">{{ review.user }} [ {{ review.date|date:'d/m/Y' }} ]</span>
                </div>
            </div>

        </div>
        <hr>
        <p>
            {{ review.comment }}
        </p>
    </div>
{% endblock %}