dishes/urls.py
from django.urls import path
from dishes import views

app_name = 'dishes'

urlpatterns = [
    path('cart', views.CartListView.as_view(), name='cart'),
    path('get_cart_items', views.get_cart_items, name='get-cart-items'),
    path('remove_from_cart', views.remove_from_cart, name='remove-from-cart'),
    path('add_to_cart', views.add_dish_to_cart, name='add-dish-to-cart'),
    path('order/<int:pk>/recap', views.OrderRecapView.as_view(), name='order-recap'),
    path('order/<int:pk>/complete', views.OrderCompleteView.as_view(), name='order-complete'),
    path('order/<int:pk>/detail', views.OrderDetailView.as_view(), name='order-detail'),
    path('order/list', views.OrderListView.as_view(), name='order-list'),

    path('review/add/<int:pk>', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>/detail', views.ReviewDetailView.as_view(), name='review-detail'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),

    path('menu', views.MenuView.as_view(), name='menu'),
    path('dish/add', views.DishAddView.as_view(), name='add-dish'),
    path('dish/<int:pk>/detail', views.DishDetailView.as_view(), name='dish-detail'),
    path('dish/<int:pk>/update', views.DishUpdateView.as_view(), name='dish-update'),
    path('dish/<int:pk>/delete', views.DishDeleteView.as_view(), name='dish-delete'),
    path('dish/search', views.search_dishes, name='dish-search'),
    path('dish/search/view', views.DishSearchView.as_view(), name='dish-search-view'),
]

restaurant_project/urls.py
import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from restaurant_project import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('dishes/', include('dishes.urls')),
    path('user_management/', include('user_management.urls')),
    path('user_management/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('profile/create', views.ProfileCreateView.as_view(), name='profile-create'),
    path('profile', views.ProfileDetailView.as_view(), name='profile'),
    path('profile/update', views.ProfileUpdateView.as_view(), name='profile-update'),

    path('user/register', views.UserCreateView.as_view(), name='user-register'),
    path('user/login', views.UserLoginView.as_view(), name='login'),
    path('user/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user/update_email', views.UserUpdateEmailView.as_view(), name='user-update-email'),
    path('user/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    path('check_email_unique', views.check_email_is_unique, name='check-email-is-unique'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
]

user_management/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from dishes.models import OrderHeader, Dish
from restaurant_project import settings


class PlatformUser(AbstractUser):
    """
    Model that represent a user of the application. The username field is the
    email field.
    """
    AbstractUser._meta.get_field('email')._unique = True
    terms_of_service_acceptance = models.BooleanField(default=False)
    terms_of_service_acceptance_datetime = models.DateTimeField(auto_now_add=True)
    is_manager = models.BooleanField(default=False)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    def clean(self):
        """
        A user have to accept the term of services.
        :return: Exception.
        """
        if not self.terms_of_service_acceptance:
            raise ValidationError(_("You must accept the terms of services"))

    class Meta:
        verbose_name = _('platform user')
        verbose_name_plural = _('platform users')


class Profile(models.Model):
    """
    Model that represent a profile of a correctly registered user.
    """
    A_ZONE = 'A'
    B_ZONE = 'B'
    C_ZONE = 'C'
    D_ZONE = 'D'
    ZONES = [
        (A_ZONE, _('A - Centro storico di Modena')),
        (B_ZONE, _('B - Zona urbana di Modena')),
        (C_ZONE, _('C - Frazioni di Modena')),
        (D_ZONE, _('D - Provincia di Modena')),
    ]
    DELIVERY_TIME = {
        A_ZONE: 5,
        B_ZONE: 10,
        C_ZONE: 15,
        D_ZONE: 30
    }
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    street = models.CharField(max_length=120, null=True, blank=True)
    number = models.PositiveIntegerField(null=True, blank=True)
    city = models.CharField(max_length=120, null=True, blank=True)
    province = models.CharField(max_length=120, null=True, blank=True)
    zip = models.CharField(max_length=5, null=True, blank=True)
    zone = models.CharField(max_length=2, choices=ZONES, null=True, blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='profile'
    )

    class Meta:
        ordering = ['-last_name', 'first_name']

    def __str__(self):
        return f'Profilo di {self.first_name} {self.last_name}'

    def create_cart(self):
        """
        When a user is created or when he complete his current order, a new
        cart is created.
        """
        cart = OrderHeader.objects.create(user=self.user)
        cart.code = _(f'ORDINE # {cart.pk}')
        cart.save()

    @property
    def get_address(self):
        """
        If all the address components are correctly stored, returns them
        otherwise returns None
        :return: The user address or None.
        """
        if self.city and self.street and self.number and self.province and self.zip and self.zone:
            return f'{self.street} {self.number}, {self.city} ({self.province}) - {self.zip} [{self.zone}]'
        else:
            return None

    @property
    def get_cart(self):
        """
        Returns the current user cart.
        :return: User cart.
        """
        return OrderHeader.objects.get(user=self.user, state=OrderHeader.CART)

    @property
    def get_expected_delivery_time(self):
        """
        Retrieves the delivery time from the dictionary inside the model.
        :return: The expected delivery time.
        """
        return self.__class__.DELIVERY_TIME[self.zone]

    @property
    def get_orders_count(self):
        """
        Returns the sum of all the orders made by the current user.
        :return: The number of orders made by the user.
        """
        return OrderHeader.objects.filter(user=self.user).exclude(state=OrderHeader.CART).count()

    @property
    def get_all_ordered_dishes(self):
        """
        Returns all the ordered dishes grouped in categories.
        :return: A dictionary that have the categories as keys and lists of dishes as values.
        """
        orders = OrderHeader.objects.filter(user=self.user).exclude(state=OrderHeader.CART)
        categories = Dish.get_dish_categories()

        for order in orders:
            for item in order.get_items:
                categories[item.dish.category].extend([item.dish
                                                       for item in order.get_items
                                                       if item.dish not in categories[item.dish.category]])
        return categories

user_management/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, TemplateView, UpdateView
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import View

from user_management.forms import PlatformUserCreationForm, ProfileCrispyForm, PlatformUserEmailOnlyForm, LoginForm
from user_management.models import PlatformUser, Profile

account_activation_token = PasswordResetTokenGenerator()


################ USER ################


class UserCreateView(CreateView):
    """
    View to create a new user.
    """
    form_class = PlatformUserCreationForm
    template_name = 'registration/user_crispy_create.html'
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        """
        A user need to confirm his email before gaining access to the web
        application.
        :param form: PlatformUser form.
        :return: HTTP response.
        """
        response = super(UserCreateView, self).form_valid(form)

        mail_subject = _('Spoon Corner: Conferma account')
        relative_confirm_url = reverse(
            'user_management:verify-user-email',
            args=[
                urlsafe_base64_encode(force_bytes(self.object.pk)),
                account_activation_token.make_token(self.object)
            ]
        )
        self.object.email_user(
            subject=mail_subject,
            message=(f'Ciao {self.object.username}, \n\n'
                     f'Benvenuto sul nostro sito!\n'
                     f'Clicca il link seguente per confermare il tuo account: \n'
                     f'{self.request.build_absolute_uri(relative_confirm_url)}\n'
                     f'\n'
                     f'A presto,\n'
                     f'Il team di Spoon Corner'),
        )
        self.object.token_sent = True
        # until the user confirms his email, he is inactive
        self.object.is_active = False
        self.object.save()
        return response


class UserLoginView(LoginView):
    """
    View to display the login form.
    """
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('homepage')


class UserUpdateEmailView(LoginRequiredMixin, UpdateView):
    """
    View to update the email of a user.
    """
    model = PlatformUser
    template_name = 'user_management/email_crispy_update.html'
    form_class = PlatformUserEmailOnlyForm
    success_url = reverse_lazy('user_management:profile')

    def get_object(self, queryset=None):
        """
        Returns the requested user.
        """
        return PlatformUser.objects.get(pk=self.request.user.pk)

    def post(self, request, *args, **kwargs):
        """
        In order to manage the cancel button from the dish form. If 'cancel'
        is in the request.POST, the dish must not be updated.
        :return: HTTP response.
        """
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy('user_management:profile'))
        else:
            return super(UserUpdateEmailView, self).post(request, *args, **kwargs)


class UserDeleteView(LoginRequiredMixin, View):
    """
    View to delete an existing platform user.
    """
    def get(self, request, *args, **kwargs):
        PlatformUser.objects.get(pk=self.request.user.pk).delete()
        return HttpResponseRedirect(reverse_lazy('user_management:login'))

    def post(self, request, *args, **kwargs):
        PlatformUser.objects.get(pk=self.request.user.pk).delete()
        return HttpResponseRedirect(reverse_lazy('user_management:login'))


################ PROFILE ################


class ProfileCreateView(LoginRequiredMixin, CreateView):
    """
    View to display
    """
    form_class = ProfileCrispyForm
    template_name = 'registration/profile_crispy_create.html'
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.create_cart()
        return super(ProfileCreateView, self).form_valid(form)


class ProfileDetailView(LoginRequiredMixin, TemplateView):
    """
    View to display the profile of the authenticated user.
    """
    template_name = 'user_management/user_profile.html'
    profile = None

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        try:
            self.profile = get_object_or_404(Profile, user=self.request.user)
        except ObjectDoesNotExist:
            raise Http404

        return context


class ProfileUpdateView(UpdateView, LoginRequiredMixin):
    """
    View to update the information about the profile of an authenticated user.
    """
    model = Profile
    template_name = 'user_management/profile_crispy_update.html'
    form_class = ProfileCrispyForm
    success_url = reverse_lazy('user_management:profile')

    def get_object(self, queryset=None):
        """
            Returns the requested profile.
        """
        return Profile.objects.get(user=self.request.user)

    def post(self, request, *args, **kwargs):
        """
        In order to manage the cancel button from the dish form. If 'cancel'
        is in the request.POST, the dish must not be updated.
        :return: HTTP response.
        """
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy('user_management:profile'))
        else:
            return super(ProfileUpdateView, self).post(request, *args, **kwargs)


################ AJAX REQUESTS ################


def check_username_is_unique(request):
    """
    Function called by an ajax request, it checks if the given username is
    unique inside the platform.
    :return: The check results.
    """
    user = None
    username = request.GET.get('username', False)
    if username:
        user = PlatformUser.objects.filter(username=username)
    return JsonResponse({'is_not_unique': True if user else False})


def check_email_is_unique(request):
    """
    Function called by an ajax request, it checks if the given email is
    unique inside the platform.
    :return: The check results.
    """
    user = None
    email = request.GET.get('email', False)
    if email:
        user = PlatformUser.objects.filter(email=email)  # deve anche avere l'id diverso dallo user corrente!
    return JsonResponse({'is_not_unique': True if user else False})


def user_login_by_token(request, user_id_b64=None, user_token=None):
    """
    Function to check if the current user is correctly related to his user_id
    and his token.
    :param request: The current request.
    :param user_id_b64: The user_id in base 64.
    :param user_token: The user token.
    :return:
    """
    try:
        uid = force_text(urlsafe_base64_decode(user_id_b64))
        user = PlatformUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, PlatformUser.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, user_token):
        user.is_active = True
        user.save()
        login(request, user)
        return True

    return False


def verify_user_email(request, user_id_b64=None, user_token=None):
    """
    View to check if the current user is correctly related to his user_id
    and his token, if it's true, the user can create his platoform profile.
    :param request: The current request.
    :param user_id_b64: The user_id in base 64.
    :param user_token: The user token.
    :return:
    """
    if not user_login_by_token(request, user_id_b64, user_token):
        message = _('Errore: Tentativo di validazione email per l\'utente {user} con token {token}')
        subject = _('Errore di autenticazione')
        # in this case manager and admin are the same entity
        manager = PlatformUser.objects.get(is_manager=True)
        manager.email_user(subject=subject, message=message)
    return redirect('user_management:profile-create')


def login_user_for_password_reset(request, user_id_b64=None, user_token=None):
    """
    View to check if the current user is correctly related to his user_id
    and his token, if it's true, the user can reset his password.
    :param request: The current request.
    :param user_id_b64: The user_id in base 64.
    :param user_token: The user token.
    :return:
    """
    if not user_login_by_token(request, user_id_b64, user_token):
        message = 'Errore: Tentativo di reset password non autorizzato per l\'utente {user} con token {token}'
        subject = _('Errore di reset password')
        # in this case manager and admin are the same entity
        manager = PlatformUser.objects.get(is_manager=True)
        manager.email_user(subject=subject, message=message)

        return redirect('homepage')
    return redirect('user_background:set-new-password')

user_management/templates/user_management/email_crispy_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Template to display the update email form.
{% endcomment %}

{% block title %}Modifica la tua email{% endblock %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        .jumbotron {
            background-image: url("{% static 'img/nastuh-abootalebi-yWwob8kwOCk-unsplash.jpg' %}");
            background-size: cover;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Aggiorna la tua email</h2>
            <p class="lead">Tramite email verranno comunicate le informazioni sui tuoi ordini.</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% include 'user_management/base/base_user_crispy_update.html' %}
{% endblock %}

{% block javascript %}
    <script>
        $(function () {
            $('#id_email').change(function () {
                console.log($(this).val());
                $.ajax({
                    type: 'GET',
                    url: '{% url 'user_management:check-email-is-unique' %}',
                    data: {
                        'email' : $(this).val()
                    },
                    dataType: "json",
                    success: function (data) {
                        if (data.is_not_unique) {
                            $('.alert-email').show();
                            $('#submit-id-submit').hide();
                        } else {
                            $('.alert-email').hide();
                            $('#submit-id-submit').show();
                        }
                    }
                })
            })
        });
    </script>
{% endblock %}

user_management/templates/user_management/profile_crispy_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Template to display the update profile form.
{% endcomment %}

{% block title %}Aggiorna i dati del tuo profilo{% endblock %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        .jumbotron {
            background-image: url("{% static 'img/nastuh-abootalebi-yWwob8kwOCk-unsplash.jpg' %}");
            background-size: cover;
        }
    </style>
{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header menu">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Aggiorna il tuo profilo</h2>
            <p class="lead">Contiene le tue informazioni principali, tra cui l'indirizzo di spedizione.</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% include 'user_management/base/base_user_crispy_update.html' %}
{% endblock %}

user_management/templates/user_management/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% comment %}
    Template that displays the information about the profile of the current user.
{% endcomment %}

{% block extra_css %}
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <style>
        .jumbotron {
            background-image: url("{% static 'img/nastuh-abootalebi-yWwob8kwOCk-unsplash.jpg' %}");
            background-size: cover;
        }
    </style>
{% endblock %}

{% block title %}Profilo{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid header">
        <div class="jumbo-container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
            {% include 'navbar.html' %}
            <h2 class="jumbo-title">Il mio profilo</h2>
            <p class="lead">Visualizza le tue informazioni principali.</p>
            <div class="row">
                <div class="col d-flex justify-content-end">
                    <a href="{% url 'user_management:profile-update' %}" class="btn btn-lg btn-info"><i class="fas fa-pen"></i> Modifica profilo</a>
                </div>
                <div class="col d-flex justify-content-start">
                    <a href="#myModal" class="btn btn-lg btn-danger trigger-btn"><i class="fas fa-trash"></i> Elimina account</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box-width-radius2 container-md shadow p-4 mb-3 pl-10 bg-white w-auto">
        <div class="card-columns mt-3">

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">USERNAME</h6>
                    <p class="card-text font-weight-bold">{{ user.username }}</p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">NOME</h6>
                    <p class="card-text font-weight-bold">{{ view.profile.first_name }} {{ view.profile.last_name }}</p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">EMAIL</h6>
                    <p class="card-text font-weight-bold">{{ user.email }}</p>
                    <a href="{% url 'user_management:user-update-email' %}" class="font-weight-bold text-info">
                        Modifica <i class="far fa-edit"></i>
                    </a>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">INDIRIZZO</h6>
                    <p class="card-text font-weight-bold">
                        {% if view.profile.street %}
                            {{ view.profile.street }} {{ view.profile.number }}, {{ view.profile.city }}
                            ({{ view.profile.province }}), {{ view.profile.zip }}, Zona {{ view.profile.zone }}
                        {% else %}
                            Nessun indirizzo registrato.
                        {% endif %}
                    </p>
                </div>
            </div>

            <div class="card text-center">
                <div class="card-body">
                    <h6 class="card-title">DATA DI ISCRIZIONE</h6>
                    <div class="container">
                        <span class="card-text font-weight-bold">{{ user.date_joined|date:'l'}}</span><br>
                        <span class="card-text font-weight-bold">{{ user.date_joined|date:'d/m/Y' }}</span>
                    </div>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title"># ORDINI FATTI</h5>
                    <p class="card-text font-weight-bold">{{ user.profile.get_orders_count }}</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal HTML for deleting user account-->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminare questo account?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>
                        Questa azione non sarà reversibile. Oltre all'account verranno cancellati tutti i dati ad esso collegati.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">Annulla</button>
                    <a id="delete-user-button" type="button" class="btn btn-danger"
                       href="{% url 'user_management:user-delete' %}">Elimina</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(function () {
            $('.trigger-btn').on('click', function () {
                $('#myModal').modal('show');
            })
        });
    </script>
{% endblock %}