dishes/urls.py
from django.urls import path
from dishes import views

app_name = 'dishes'

urlpatterns = [
    path('cart', views.CartListView.as_view(), name='cart'),
    path('get_cart_items', views.get_cart_items, name='get-cart-items'),
    path('remove_from_cart', views.remove_from_cart, name='remove-from-cart'),
    path('add_to_cart', views.add_dish_to_cart, name='add-dish-to-cart'),
    path('order/<int:pk>/recap', views.OrderRecapView.as_view(), name='order-recap'),
    path('order/<int:pk>/complete', views.OrderCompleteView.as_view(), name='order-complete'),
    path('order/<int:pk>/detail', views.OrderDetailView.as_view(), name='order-detail'),
    path('order/list', views.OrderListView.as_view(), name='order-list'),

    path('review/add/<int:pk>', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>/detail', views.ReviewDetailView.as_view(), name='review-detail'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),

    path('menu', views.MenuView.as_view(), name='menu'),
    path('dish/add', views.DishAddView.as_view(), name='add-dish'),
    path('dish/<int:pk>/detail', views.DishDetailView.as_view(), name='dish-detail'),
    path('dish/<int:pk>/update', views.DishUpdateView.as_view(), name='dish-update'),
    path('dish/<int:pk>/delete', views.DishDeleteView.as_view(), name='dish-delete'),
    path('dish/search', views.search_dishes, name='dish-search'),
    path('dish/search/view', views.DishSearchView.as_view(), name='dish-search-view'),
]

restaurant_project/urls.py
import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from restaurant_project import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('dishes/', include('dishes.urls')),
    path('user_management/', include('user_management.urls')),
    path('user_management/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('profile/create', views.ProfileCreateView.as_view(), name='profile-create'),
    path('profile', views.ProfileDetailView.as_view(), name='profile'),
    path('profile/update', views.ProfileUpdateView.as_view(), name='profile-update'),

    path('user/register', views.UserCreateView.as_view(), name='user-register'),
    path('user/login', views.UserLoginView.as_view(), name='login'),
    path('user/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user/update_email', views.UserUpdateEmailView.as_view(), name='user-update-email'),
    path('user/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    path('check_email_unique', views.check_email_is_unique, name='check-email-is-unique'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="it">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/bread.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block jumbotron %}{% endblock %}
<div id="site-main-page" class="container mt-n1 mt-md-3">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="{% static 'js/base_scripts.js' %}"></script>
{% include 'dishes/base/get_items_number_ajax.html' %}
{% block javascript %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% comment %}
    Template to display the Home page.
{% endcomment %}

{% block extra_css %}
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column text-center">
        {% include 'navbar.html' %}
        <main role="main" class="inner cover">
            <h1 class="cover-heading">Benvenuto su Spoon Corner</h1>
            <p class="lead">Il cibo a casa, come non lo hai mai visto.</p>
            <p class="lead">
                <a href="{% url 'dishes:menu' %}" class="btn btn-lg btn-secondary">Visualizza il menù</a>
            </p>
        </main>
        <footer class="mastfoot mt-auto">
        </footer>
    </div>
{% endblock %}

templates/navbar.html
{% comment %}
    Template to display the navbar of the website.
{% endcomment %}

{% load notifications_tags %}

<header class="masthead mb-auto">
    <div class="inner">
        <a href="{% url 'homepage' %}" class="h3 masthead-brand">Spoon Corner</a>
        <nav class="nav nav-masthead justify-content-center">
            {#            <a id="Home" class="nav-link" href="{% url 'homepage' %}">Home</a>#}
            <a id="Menu" class="nav-link" href="{% url 'dishes:menu' %}">Menu</a>
            {% if not user.is_authenticated %}
                <a id="Accedi" class="nav-link" href="{% url 'user_management:login' %}">Accedi</a>
            {% else %}
                <a id="Ordini" class="nav-link" href="{% url 'dishes:order-list' %}">Ordini</a>
                {% if not user.is_manager %}
                    <a id="Profilo" class="nav-link" href="{% url 'user_management:profile' %}">Profilo</a>
                {% endif %}
                <a id="Notifiche" class="nav-link" href="{% url 'notifications:unread' %}">
                    <i class="fas fa-bell"></i>
                    {% live_notify_badge badge_class="badge badge-pill badge-light" %}
                </a>
                {% if not user.is_manager %}
                    <a id="Carrello" class="nav-link" href="{% url 'dishes:cart' %}"><i class="fas fa-shopping-cart"></i> <span class="badge badge-pill badge-light"></a>
                {% endif %}
                <a id="Esci" class="nav-link" href="{% url 'user_management:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
            {% endif %}
        </nav>
    </div>
</header>

templates/searchbar.html
{% comment %}
    Template to display the searchbar of the Menu page.
{% endcomment %}

<form action="{% url 'dishes:dish-search-view' %}" method="get">
    <div class="input-group md-form form-sm form-1 pl-0">
        <div class="input-group-prepend">
    <span class="input-group-text bg-white" id="basic-text1"><i class="fas fa-search"
                                                                aria-hidden="true"></i></span>
        </div>
        <input class="form-control my-0 py-1 search-input" type="search" placeholder="Cerca un piatto"
               aria-label="Cerca un piatto" name="search" autocomplete="off">
    </div>
</form>
<div class="search-results">
</div>