dishes/urls.py
from django.urls import path
from dishes import views

app_name = 'dishes'

urlpatterns = [
    path('cart', views.CartListView.as_view(), name='cart'),
    path('get_cart_items', views.get_cart_items, name='get-cart-items'),
    path('remove_from_cart', views.remove_from_cart, name='remove-from-cart'),
    path('add_to_cart', views.add_dish_to_cart, name='add-dish-to-cart'),
    path('order/<int:pk>/recap', views.OrderRecapView.as_view(), name='order-recap'),
    path('order/<int:pk>/complete', views.OrderCompleteView.as_view(), name='order-complete'),
    path('order/<int:pk>/detail', views.OrderDetailView.as_view(), name='order-detail'),
    path('order/list', views.OrderListView.as_view(), name='order-list'),

    path('review/add/<int:pk>', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>/detail', views.ReviewDetailView.as_view(), name='review-detail'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),

    path('menu', views.MenuView.as_view(), name='menu'),
    path('dish/add', views.DishAddView.as_view(), name='add-dish'),
    path('dish/<int:pk>/detail', views.DishDetailView.as_view(), name='dish-detail'),
    path('dish/<int:pk>/update', views.DishUpdateView.as_view(), name='dish-update'),
    path('dish/<int:pk>/delete', views.DishDeleteView.as_view(), name='dish-delete'),
    path('dish/search', views.search_dishes, name='dish-search'),
    path('dish/search/view', views.DishSearchView.as_view(), name='dish-search-view'),
]

restaurant_project/urls.py
import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from restaurant_project import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('dishes/', include('dishes.urls')),
    path('user_management/', include('user_management.urls')),
    path('user_management/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/models.py
from statistics import mean

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from restaurant_project import settings


class Dish(models.Model):
    """
    Model that represent a dish, a dish is created by the manager account.
    """
    images_path = 'uploads/'
    MAIN = 'MD'
    BURGER = 'BU'
    SIDE = 'SI'
    DESSERT = 'DE'
    CATEGORY_CHOICES = [
        (MAIN, _('Piatto principale')),
        (BURGER, _('Burger')),
        (SIDE, _('Contorno')),
        (DESSERT, _('Dessert')),
    ]
    name = models.CharField(max_length=150, unique=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=MAIN)
    ingredients = models.TextField(max_length=255)
    cook_time = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.ImageField(upload_to=images_path,
                              default=images_path + 'bread.png')

    @classmethod
    def get_dish_categories(cls):
        """
        Returns a dictionary with all the possible categories of a dish as keys and
        empty arrays as values.
        :return: a dictionary with a set of empty arrays for each category.
        """
        return {category: [] for category, description in cls.CATEGORY_CHOICES}

    @property
    def get_reviews(self):
        """
        Returns all the reviews associated to the current dish.
        :return: The review queryset.
        """
        return Review.objects.filter(dish=self)

    @property
    def get_avg_revs(self):
        """
        Returns the average score of the reviews related to the dish.
        :return: The average value rounded to one decimal position.
        """
        revs_list = Review.objects.filter(dish=self).values_list('stars', flat=True)
        return round(mean(revs_list), 1) if len(revs_list) > 0 else 0

    def __repr__(self):
        return self.name

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['-pk']
        verbose_name_plural = _('Dishes')


class Review(models.Model):
    """
    Model that represent a Review for a Dish, a review is written by a registered user.
    """
    title = models.CharField(max_length=150)
    stars = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_reviews')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name='dish_reviews')
    comment = models.TextField(max_length=2000)
    date = models.DateTimeField(default=timezone.now)

    def __repr__(self):
        return f'[ {self.title} - {self.stars} ] di {self.user}'

    def __str__(self):
        return f'[ {self.title} - {self.stars} ] di {self.user}'

    class Meta:
        ordering = ['-date']


class OrderHeader(models.Model):
    """
    Model that represent an Order, every order is created as a CART when the
    user create his profile or when he complete an order from the "Cart" page.
    """
    CART = 'CA'
    ORDERED = 'OR'
    PROCESSED = 'PR'
    SHIPPED = 'SH'  # at home
    READY = 'RE'  # takeaway
    DONE = 'DO'
    ORDER_STATES = [
        (CART, _('Carrello')),
        (ORDERED, _('Ordinato')),
        (PROCESSED, _('In preparazione')),
        (READY, _('Pronto')),
        (SHIPPED, _('In consegna')),
        (DONE, _('Completato')),
    ]
    code = models.CharField(max_length=150, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_orders')
    amount = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    state = models.CharField(max_length=2, choices=ORDER_STATES, default=CART)
    delivery_type = models.BooleanField(default=False)  # False --> takeaway, True --> at home
    date = models.DateTimeField(default=timezone.now)
    date_change_state = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(max_length=255, null=True, blank=True)

    @property
    def get_items(self):
        """
        Gets all the items associated to the current order (self).
        :return: queryset of the items associated to the current order.
        """
        return OrderItem.objects.filter(order=self)

    @property
    def get_items_count(self):
        """
        Gets number of the pieces of the items associated to the current order.
        :return: number of the pieces (integer).
        """
        return sum(OrderItem.objects.filter(order=self).values_list('pieces', flat=True))

    @property
    def get_amount(self):
        """
        Gets the amount of the current order, based on the sum of the price of
        all the order items.
        :return: total amount (integer)
        """
        return sum(list(OrderItem.objects.filter(order=self).values_list('price', flat=True)))

    @property
    def get_lexical_state(self):
        """
        Retrieves the lexical version of the current order state.
        :return: The description of the order state.
        """
        return [description
                for state, description in OrderHeader.ORDER_STATES
                if state == self.state][0]

    def __str__(self):
        return f'Ordine in stato {self.state} di {self.user}'

    def __repr__(self):
        return f'Ordine in stato {self.state} di {self.user}'

    class Meta:
        ordering = ['-date_change_state']


class OrderItem(models.Model):
    """
    Model that represent an order item, an order item is created when a user
    add a new dish in the cart.
    """
    order = models.ForeignKey(OrderHeader, on_delete=models.CASCADE, related_name='order_items')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name='dish_orders')
    pieces = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    notes = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return f'Elemento {self.dish} dell\'ordine {self.order}'

    def __repr__(self):
        return f'Elemento {self.dish} dell\'ordine {self.order}'

dishes/forms.py
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Row, Column, Submit, Field
from django import forms
from django.utils.translation import gettext_lazy as _

from dishes.models import Dish, OrderHeader, Review


class DishForm(forms.ModelForm):
    """
    Form used to create or update a dish.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['name'].widget.attrs['placeholder'] = _('Nome piatto')
        self.fields['ingredients'].widget.attrs['placeholder'] = _('Lista degli ingredienti...')
        self.fields['cook_time'].widget.attrs['placeholder'] = _('Tempo di preparazione')
        self.fields['price'].widget.attrs['placeholder'] = _('Prezzo del piatto')
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'dish-add-crispy-form'
        self.helper.form_class = ''
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='col-md-6 mb-0'),
                Column(Field('category', css_class='custom-select'), css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(Column('image', css_class='mb-0'), css_class='grey-text'),
            Row(
                Column(AppendedText('cook_time', 'min', active=True), css_class='col-md-6 mb-0'),
                Column(AppendedText('price', '€', active=True), css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(Column(Field('ingredients', type='textarea'), css_class='mb-0'), css_class='grey-text'),
            Submit('submit', _('Salva'), css_class='btn btn-info'),
            Submit('cancel', _('Annulla'), css_class='btn btn-danger', formnovalidate='formnovalidate'),
        )

    class Meta:
        model = Dish
        fields = (
            'name',
            'category',
            'ingredients',
            'cook_time',
            'price',
            'image',
        )
        labels = {
            'name': 'Nome del piatto',
            'category': 'Categoria',
            'ingredients': 'Ingredienti',
            'cook_time': 'Tempo di preparazione (min)',
            'price': 'Prezzo',
            'image': 'Foto del piatto',
        }


class OrderHeaderForm(forms.ModelForm):
    """
    Form to update an order state (if the user is a manager).
    """
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('initial', None).pop('user', None)
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['code'].disabled = True
        self.fields['amount'].disabled = True
        if not user.is_manager:
            self.fields['state'].disabled = True
        self.fields['delivery_type'].disabled = True
        self.fields['date'].disabled = True
        self.fields['notes'].disabled = True
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'order-detail-crispy-form'
        self.helper.form_class = ''
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(
                Column('code', css_class='col-md-6 mb-0'),
                Column(AppendedText('amount', '€', active=True), css_class='col-md-3 mb-0'),
                Column('delivery_type', css_class='col-md-3 mb-0 pl-5 mt-4 custom-control custom-switch'),
                css_class='d-flex align-items-center grey-text'
            ),
            Row(
                Column(Field('state', css_class='custom-select'), css_class='col-md-6 mb-0'),
                Column('date', css_class='col-md-6 mb-0'),
                css_class='grey-text'
            ),
            Row(
                Column(Field('notes', type='textarea', rows="3"), css_class='mb-0'), css_class='grey-text'
            )
        )
        if kwargs['instance'].delivery_type:
            self.helper.layout.append(
                HTML("""
                    <hr>
                    <h4 class="font-weight-light">
                        Tempo di consegna previsto: {{ orderheader|get_preparation_time:orderheader.user }} minuti 
                        <i class="far fa-clock"></i>
                    </h4>
                """)
            )
        else:
            self.helper.layout.append(
                HTML("""
                    <hr>
                    <h4 class="font-weight-light">
                        Tempo di preparazione previsto: {{ orderheader|get_preparation_time:orderheader.user }} minuti 
                        <i class="far fa-clock"></i>
                    </h4>
                """)
            )
        if user.is_manager:
            self.helper.add_input(Submit('submit', _('Aggiorna'), css_class='btn btn-info'))
            self.helper.add_input(Submit('cancel', _('Annulla'),
                                         css_class='btn btn-danger',
                                         formnovalidate='formnovalidate'))

    class Meta:
        model = OrderHeader
        fields = (
            'code',
            'amount',
            'state',
            'delivery_type',
            'date',
            'notes',
        )
        labels = {
            'code': 'Codice ordine',
            'amount': 'Totale',
            'state': 'Stato ordine',
            'delivery_type': 'Domicilio',
            'date': 'Data ordine',
            'notes': 'Note',
        }


class ReviewForm(forms.ModelForm):
    """
    Form used to create or update a review.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Default form settings
        self.fields['title'].widget.attrs['placeholder'] = _('Titolo')
        self.fields['comment'].widget.attrs['placeholder'] = _('Scrivi la tua esperienza...')
        # Crispy settings
        self.helper = FormHelper()
        self.helper.form_id = 'review-add-crispy-form'
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(HTML(
                """
                    <label>Valutazione complessiva *</label>
                    <div class="form-group">
                        <fieldset class="rating">
                            <input type="radio" id="star5" name="stars" value="5" />
                            <label for="star5">5 stars</label>
                            <input type="radio" id="star4" name="stars" value="4" />
                            <label for="star4">4 stars</label>
                            <input type="radio" id="star3" name="stars" value="3" />
                            <label for="star3">3 stars</label>
                            <input type="radio" id="star2" name="stars" value="2" />
                            <label for="star2">2 stars</label>
                            <input type="radio" id="star1" name="stars" value="1" />
                            <label for="star1">1 star</label>
                        </fieldset>
                    </div>
                """
            ), css_class='d-flex flex-column grey-text'),
            Row(
                Column('title', css_class='col-md mb-0'), css_class='grey-text'
            ),
            Row(
                Column(Field('comment', type='textarea', rows="5"), css_class='mb-0 grey-text'),
            ),
            Submit('submit', _('Salva'), css_class='btn btn-info'),
            Submit('cancel', _('Annulla'), css_class='btn btn-danger', formnovalidate='formnovalidate'),
        )

    class Meta:
        model = Review
        fields = (
            'title',
            'stars',
            'comment'
        )
        labels = {
            'title': 'Titolo',
            'stars': 'Voto',
            'comment': 'Commento'
        }

dishes/templates/dishes/base/add_to_cart_ajax.html
{% comment %}
    Base template to insert the add to cart ajax request.
{% endcomment %}

<script>
    function addToCartAjax(jsonData) {
        $.ajax({
            type: 'POST',
            url: "{% url 'dishes:add-dish-to-cart' %}",
            data: {
                'order_item': JSON.parse(jsonData),
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            success: function (data) {
                getItemsNumberAjax();
                if (document.title === 'Carrello') {
                    console.log(data);
                    // andiamo ad aggiornare i nuovi valori dell'item modificato! (commenta meglio)
                    $('.list-group li').each(function () {
                        if ($(this).find('.dish-title').text() === data.dish_name) {
                            $(this).find('.item-pieces').text(data.item_pieces);
                            $(this).find('.price').text((parseFloat(data.item_price).toFixed(2)).replace('.', ','));
                        }
                    });
                    $('#cart-amount').text(data.cart_amount.replace('.', ','));
                }
                $('#cart-modal').modal('hide');
            }
        });
    }

    $(function () {
        $('.amount').on('click', function () {
            let amount = parseFloat($(this).text().split(' ')[1]).toFixed(2);
            let dishName = $(this).closest('.modal-content').find('.modal-title').text();
            let quantity = $(this).closest('.modal-content').find('#item-pieces').val();
            let jsonData;
            console.log(amount);
            if (document.title === 'Menu') {
                jsonData = '{"dish_name": "' + dishName + '", "quantity": ' + quantity + ', "amount": ' + amount + '}';
            } else if (document.title === 'Carrello') {
                let dishPk = $('.dish-pk').text();
                jsonData = '{"dish_name": "' + dishName + '", "quantity": ' + quantity + ', "amount": ' + amount
                    + ', "dish_pk": ' + dishPk + '}';
            }
            if (amount > 0) {
                addToCartAjax(jsonData);
            } else {
                alert('Errore: selezionare una quantità corretta (almeno uno)!');
            }
        });
    });
</script>

dishes/templates/dishes/base/base_cart_item.html
{% comment %}
    Base template to display an item inside the cart list in the Cart page.
{% endcomment %}

<li class="dish-content list-group-item">
    <div class="row">
        <div class="col d-flex align-items-center">
            <a href="#cart-modal" class="btn btn-transparent list-link cart-link">
                <i class="fas fa-pen"></i>
            </a>
            &nbsp;
            <span class="text-muted"><span class="item-pieces">{{ item.pieces }}</span>x &nbsp;</span>
            <span class="dish-title">{{ dish.name }}</span>
            <span class="dish-pk" style="display: none">{{ dish.pk }}</span>
        </div>
        <div class="col d-flex align-items-center justify-content-end">
            <span class="price">{{ item.price }} €</span>&nbsp;
            <a href="#delete" class="btn btn-transparent list-link cart-remove">
                <i class="fas fa-trash"></i>
                <span class="item-pk" style="display: none">{{ item.pk }}</span>
            </a>
        </div>
    </div
</li>

dishes/templates/dishes/base/base_category_list.html
{% comment %}
    Base template to display all the dishes inside a given category in the Menu and Search Results pages.
{% endcomment %}

<div class="row row-cols-2 pt-3">
    {% for dish in dish_list %}
        <div class="col">
            <div class="shadow card mb-3" style="max-width: 540px; border: none;">
                <div class="row no-gutters">
                    <div class="col-md-4 card-img" style="background-image: url('{{ dish.image.url }}');">
                    </div>
                    <div class="col-md-8 pl-2">
                        <div class="card-body dish-content">
                            <div class="row d-flex align-items-start justify-content-between">
                                <a href="{% url 'dishes:dish-detail' dish.pk %}" class="card-link">
                                    <h5 class="card-title dish-title text text-wrap">{{ dish.name }}</h5>
                                </a>
                                <span class="border-item">
                                    {{ dish.get_avg_revs }} &nbsp;<i class="fas fa-star"></i>
                                </span>
                            </div>
                            <div class="row"><p class="card-text ingredients text font-weight-light">{{ dish.ingredients }}</p></div>
                            <div class="row">
                                <p class="card-text">
                                    <small class="text-muted">
                                        Tempo di preparazione: {{ dish.cook_time }} min
                                    </small>
                                </p>
                            </div>
                            <div class="row mt-2 d-flex justify-content-between">
                                <span class="price">{{ dish.price }} €</span>
                                {% if user.is_authenticated %}
                                    <a href="#cart-modal" class="cart-link card-link border-item"> <!-- data-toggle="modal" data-target="#cart-modal">-->
                                        <span>Aggiungi al carrello <i class="fas fa-shopping-cart"></i></span>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="col-lg text-center">
            <p class="lead">Nessun piatto per ora!</p>
        </div>
    {% endfor %}
</div>

dishes/templates/dishes/base/base_dishes_list.html
{% comment %}
    Base template to display the tab menu with all the categories inside the Menu and Search results pages.
{% endcomment %}

<ul class="nav nav-tabs nav-fill mt-2" id="menu-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active lead" id="main-tab{{ rec }}" data-toggle="tab" href="#main-dish{{ rec }}" role="tab" aria-controls="main" aria-selected="true">Piatti principali</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link lead" id="burger-tab{{ rec }}" data-toggle="tab" href="#burger{{ rec }}" role="tab" aria-controls="burger" aria-selected="false">Burger</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link lead" id="side-tab{{ rec }}" data-toggle="tab" href="#side{{ rec }}" role="tab" aria-controls="side" aria-selected="false">Contorni</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link lead" id="dessert-tab{{ rec }}" data-toggle="tab" href="#dessert{{ rec }}" role="tab" aria-controls="dessert" aria-selected="false">Dessert</a>
    </li>
</ul>
<div class="tab-content mb-2" id="myTabContent">
    <div class="tab-pane fade show active" id="main-dish{{ rec }}" role="tabpanel" aria-labelledby="main-tab">
        {% if rec %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_main_dishes|exclude_ordered_dishes:user %}
        {% else %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_main_dishes %}
        {% endif %}
    </div>
    <div class="tab-pane fade" id="burger{{ rec }}" role="tabpanel" aria-labelledby="burger-tab">
        {% if rec %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_burgers|exclude_ordered_dishes:user %}
        {% else %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_burgers %}
        {% endif %}
    </div>
    <div class="tab-pane fade" id="side{{ rec }}" role="tabpanel" aria-labelledby="side-tab">
        {% if rec %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_sides|exclude_ordered_dishes:user %}
        {% else %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_sides %}
        {% endif %}
    </div>
    <div class="tab-pane fade" id="dessert{{ rec }}" role="tabpanel" aria-labelledby="dessert-tab">
        {% if rec %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_desserts|exclude_ordered_dishes:user %}
        {% else %}
            {% include 'dishes/base/base_category_list.html' with dish_list=dish_list|get_desserts %}
        {% endif %}
    </div>
</div>

dishes/templates/dishes/base/base_order_confirmation.html
{% comment %}
    Base template to display the order confirmation footer inside the cart page, only if the cart has one item at least.
{% endcomment %}

<div class="confirmation-div box-width-radius2 container-md shadow p-4 mb-3 pl-10
            bg-white w-auto">
    <form action="{% url 'dishes:order-recap' orderheader.pk %}" method="post">{% csrf_token %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row">
                    <div class="col">
                        <h4 class="font-weight-light">Tipo di consegna:</h4>
                    </div>
                    <div class="col d-flex justify-content-end">
                        <div class="custom-control custom-switch">
                            {% if user.profile.get_address %}
                                <input type="checkbox" class="custom-control-input delivery-option switch switch-lg" id="deliveryType" name="deliveryType" checked>
                                <label class="custom-control-label " for="deliveryType">Consegna a domicilio</label>
                                <i class="fas fa-info-circle tooltip-test" title="{{ user.profile.get_address }}"></i>
                            {% else %}
                                <input type="checkbox" class="custom-control-input delivery-option" id="deliveryType" name="deliveryType" disabled>
                                <label class="custom-control-label" for="deliveryType">Asporto</label>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col">
                        <h1 class="font-weight-light">Totale: <span id="cart-amount">{{ amount }}</span> €</h1>
                    </div>
                    <div class="col d-flex justify-content-end">
                        <input type="submit" id="confirm" class="btn btn-lg btn-info" value="Conferma l'ordine"/>
                    </div>
                </div>
            </li>
        </ul>
    </form>
</div>

dishes/templates/dishes/base/base_order_list.html
{% comment %}
    Base template that represent a list of orders.
{% endcomment %}

<ul class="list-group list-group-flush">
    {% for order in order_list %}
        <li class="list-group-item">
            <a href="{% url 'dishes:order-detail' order.pk %}" class="list-link d-flex justify-content-between align-items-center">
                <span class="order-code btn btn-outline-secondary btn-sm">{{ order.code }}</span>
                {% if complete %}
                    <span class="badge badge-pill badge-success">{{ order.get_lexical_state }}</span>
                {% else %}
                    <span class="badge badge-pill badge-info">{{ order.get_lexical_state }}</span>
                {% endif %}
            </a>
        </li>
    {% empty %}
        <li class="list-group-item text-center">
            <p class="lead">Nessun ordine presente.</p>
        </li>
    {% endfor %}
</ul>

dishes/templates/dishes/base/base_order_list_item.html
{% comment %}
    Base template to display an order item inside the order detail page.
{% endcomment %}

<li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="{% url 'dishes:dish-detail' dish.pk %}" class="list-link">
    <div>
        <span><span class="item-pieces">{{ item.pieces }}</span>x &nbsp;</span>
        <span>{{ dish.name }}</span>
    </div>
    </a>
    <div class="d-flex align-items-center">
        <span class="price text-muted">{{ item.price }} €</span> &nbsp;&nbsp;
        <a href="{% url 'dishes:review-add' dish.pk %}" class="btn btn-outline-primary">Scrivi una recensione <i class="fas fa-pen"></i></a>
    </div>
</li>

dishes/templates/dishes/base/get_items_number_ajax.html
{% comment %}
    Base template to insert the get items number in the cart ajax request.
{% endcomment %}

<script>
    function getItemsNumberAjax() {
        $.ajax({
            type: 'GET',
            url: '{% url 'dishes:get-cart-items' %}',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                if (parseInt(data.item_number) > 0)
                    $('#Carrello').find('.badge').text(data.item_number);
                else
                    $('#Carrello').find('.badge').text('');
            }
        });
    }

    $(function () {
        {% if user.is_authenticated and not user.is_manager %}
            getItemsNumberAjax();
        {% endif %}
    });
</script>

dishes/templates/dishes/base/remove_from_cart_ajax.html
{% comment %}
    Base template to insert the remove from cart ajax request.
{% endcomment %}

<script>
    $(function () {
        $('.cart-remove').on('click', function () {
            let $listElement = $(this).closest('.dish-content');
            let dishPrice = parseFloat($(this).closest('.dish-content').find('.price').text()).toFixed(2);
            let amount = parseFloat($('#cart-amount').text()).toFixed(2)
            console.log('dish price: ' + dishPrice, 'amount: ' + amount);
            let newAmount = (amount - dishPrice).toFixed(2);

            $.ajax({
                type: 'POST',
                url: "{% url 'dishes:remove-from-cart' %}",
                data: {
                    'item_pk': $(this).find('.item-pk').text(),
                },
                headers:{
                    "X-CSRFToken": '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    $listElement.remove();
                    if (!$('.dish-list').children().length) {
                        $('.dish-list').append('<li class="dish-content list-group-item text-center">'
                            + '<p class="lead">Nessun elemento nel carrello, visualizza il nostro menu!</p>'
                            + '</li>');
                        $('.confirmation-div').hide().removeClass('d-flex');
                    }
                    $('#cart-amount').text(newAmount.replace('.', ','));
                    getItemsNumberAjax();
                }
            });
        })
    });
</script>